version: '3.7'
services:
    postgres:
        build: 
            context: ./
            dockerfile: ./img/pgres/Dockerfile
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./setup/raw_data_input:/data
            - ./temp:/temp
        ports:
            - "5432:5432"

    webserver:
        build: 
            context: ./
            dockerfile: ./img/airflow/Dockerfile 
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            # - ./plugins:/usr/local/airflow/plugins
            - ${PWD}/requirements.txt:/requirements.txt
            - ./temp:/temp
            - ./setup/raw-input_data:/data
            - ${PWD}/variables.json:/variables.json
            - ./secrets:/secrets
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
