FROM postgres:9.6

COPY ./setup/pgres/create_players_1.sql /docker-entrypoint-initdb.d
COPY ./setup/pgres/create_players_2.sql /docker-entrypoint-initdb.d
COPY ./setup/pgres/create_players_3.sql /docker-entrypoint-initdb.d
